name: Hetzner Production Deployment
env:
    SERVER_HOST: ${{ secrets.SERVER_HOST }}
    SERVER_PORT: ${{ secrets.SERVER_PORT }}
    SERVER_USER: ${{ secrets.SERVER_USER }}
    SERVER_PASS: ${{ secrets.SERVER_PASS }}
on:
    push:
        branches:
            - test
jobs:
    Deploy-Production-Hetzner:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: npm run build
      
            - name: Verify build
              run: ls -la out
      
            - name: copy file via ssh key
              uses: appleboy/scp-action@master
              env:
                  HOST:  ${{ secrets.SERVER_HOST }}
                  PORT:  ${{ secrets.SERVER_PORT }}
                  USERNAME:  ${{ secrets.SERVER_USER }}
                  PASSWORD: ${{ secrets.SERVER_PASS }}
              with:
                source: "./out"
                target: "~"
                strip_components: 2 # this is important
