name: Hetzner Production Deployment
env:
    SERVER_HOST: ${{ secrets.SERVER_HOST }}
    SERVER_PORT: ${{ secrets.SERVER_PORT }}
    SERVER_USER: ${{ secrets.SERVER_USER }}
    SERVER_PASS: ${{ secrets.SERVER_PASS }}
on:
    push:
        branches:
            - test
jobs:
    Deploy-Production-Hetzner:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            # - name: Build
            #   run: npm run build
      
            # - name: Verify build
            #   run: ls -la out
            - uses: actions/setup-node@v1
              with:
                node-version: 20
            - run: npm ci
            - run: npm run build
      
            - name: copy file via ssh key
              uses: appleboy/scp-action@master
              with:
                host:  ${{ secrets.SERVER_HOST }}
                port:  ${{ secrets.SERVER_PORT }}
                username:  ${{ secrets.SERVER_USER }}
                password: ${{ secrets.SERVER_PASS }}
                key: ${{ secrets.SERVER_KEY }}
                source: "./out"
                target: "public/"
                strip_components: 2 # this is important
