name: Hetzner Production Deployment
env:
    SERVER_HOST: ${{ secrets.SERVER_HOST }}
    SERVER_PORT: ${{ secrets.SERVER_PORT }}
    SERVER_USER: ${{ secrets.SERVER_USER }}
    SERVER_PASS: ${{ secrets.SERVER_PASS }}
on:
    push:
        branches:
            - extension

concurrency:
    group: 'hetzner-extension'
    cancel-in-progress: false

jobs:
    Deploy-Production-Hetzner:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Node Setup
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'

            - name: npm clean install
              run: npm ci

            - name: npm build
              run: npm run build

            - name: copy file via ssh key
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  port: ${{ secrets.SERVER_PORT }}
                  username: ${{ secrets.SERVER_USER }}
                  password: ${{ secrets.SERVER_PASS }}
                  key: ${{ secrets.SERVER_KEY }}
                  source: './out'
                  target: 'ext/'
                  strip_components: 2 # this is important
