name: Hetzner Production Deployment
env:
    SERVER_HOST: ${{ secrets.SERVER_HOST }}
    SERVER_PORT: ${{ secrets.SERVER_PORT }}
    SERVER_USER: ${{ secrets.SERVER_USER }}
    SERVER_PASS: ${{ secrets.SERVER_PASS }}
on:
    push:
        branches:
            - test
jobs:
    Deploy-Production-Hetzner:
        runs-on: ubuntu-latest
        steps:
            - name: Get Build Output
              uses: dawidd6/action-download-artifact@v2
              with:
                  commit: ${{ github.sha }}

            - name: Display structure of downloaded files
              run: ls -R

            - name: copy file via ssh key
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  port: ${{ secrets.SERVER_PORT }}
                  username: ${{ secrets.SERVER_USER }}
                  password: ${{ secrets.SERVER_PASS }}
                  key: ${{ secrets.SERVER_KEY }}
                  source: './out'
                  target: 'public/'
                  strip_components: 2 # this is important
